version: '1'
rules:
  - base: master
    upstream: vuejs:master # change `wei` to the owner of upstream repo
    mergeMethod: hardreset
  - base: indonesian
    upstream: master        # Required. Can be a branch in the same forked repo.
    assignees:              # Optional
      - mandaputtra
    reviewers:              # Optional
      - mandaputtra
    conflictReviewers:      # Optional, on merge conflict assign a reviewer
      - mandaputtra
label: ":arrow_heading_down: pull"  # Optional
conflictLabel: "merge-conflict"     # Optional, on merge conflict assign a custom label, Default: merge-conflict
